name: Lint
on:
  pull_request:

jobs:
  hadolint:
    runs-on: ubuntu-22.04
    name: Hadolint
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: jbergstroem/hadolint-gh-action@v1.10.0
        with:
          error_level: 2
